new languege for testing

bend is a languege that promises to a parallel running languege 

https://github.com/HigherOrderCO/Bend

it runs under a HVM and can use differnt types of complilers

the good thing about this is it can multithread proply without having to troubleshoot specific to hardware. 

Its primaraly new, so, whether it is good for the compeition is something that will need to tested. 